services:
  - type: web
    name: quickfix-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14

      - key: DATABASE_URL
        value: sqlite:///./quickfix.db

      - key: ENVIRONMENT
        value: production

      - key: UPLOAD_DIR
        value: uploads

      - key: SERVER_BASE_URL
        value: https://quickfix-ebly.onrender.com

      - key: JWT_SECRET
        generateValue: true

  - type: static
    name: quickfix-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://quickfix-ebly.onrender.com/api/v1
      - key: VITE_WS_URL
        value: wss://quickfix-ebly.onrender.com/ws
